spring:
  cloud:
    aws:
      region:
        static: eu-west-2
app:
  gov-notify:
    key: 123
    successful-submission-template-id: 00000000-0000-0000-0000-000000000000
  sqs:
    notify-queue-name: notify-queue
  sabc:
    url: https://sabc.com