spring:
  cloud:
    aws:
      region:
        static: eu-west-2
app:
  gov-notify:
    key: 123
    successful-submission-template-id: acb95826-cb75-447f-9512-52a30c734dc2
  sqs:
    notify-queue-name: notify-queue