name: Build main

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:

  build:
    if: ${{ github.event.pull_request.merged == true }}
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/gradle-build-and-publish.yml@v2.1.2
    permissions:
      contents: write
      packages: write
    with:
      integration_test_task: "integrationTest"
      create_tag: 'true'
      github_bot_username: 'laa-data-claims-notify-service'
      semgrep_check: 'false'
      java_version: 25
      jacoco_coverage_report: 'true'
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      github_app_id: ${{ vars.LAA_JAVA_SERVICE_DEPLOYER_APP_ID }}
      github_app_private_key: ${{ secrets.LAA_JAVA_SERVICE_DEPLOYER_KEY }}
      github_app_organisation: 'ministryofjustice'
